version: "3.7"

services:
  api:
    build: 
      context: ./api
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./api:app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:app
    command: npm start

  database:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

